const ADD_QUOTE = "ADD_QUOTE";
const REMOVE_QUOTE = "REMOVE_QUOTE";
const UPVOTE_QUOTE = "UPVOTE_QUOTE";
const DOWNVOTE_QUOTE = "DOWNVOTE_QUOTE";

export { ADD_QUOTE, REMOVE_QUOTE, UPVOTE_QUOTE, DOWNVOTE_QUOTE };